#!/bin/bash

# dokuwiki2mediawiki (c) 2010 by Thorsten Staerk

# This script converts a file containing dokuwiki syntax to a file containing mediawiki syntax.
# call it like: dokuwiki2mediawiki start.txt
# maturity: experimental

sed -i "s/^    \*/**/g" $@
sed -i "s/^  \*/*/g" $@
